name: Check that the code compiles.
on: [push]
jobs:
  build-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: docker pull jagholin/dosbox-gcc:latest
      - run: docker run --rm --mount type=bind,src=$(pwd),dst=/src jagholin/dosbox-gcc

